%% NN Development
% Solve an Input-Output Fitting problem with a Neural Network
% Script generated by Neural Fitting app
% Created 31-Aug-2020 14:04:12
%
% This script assumes these variables are defined:
%
%   inputs - input data.
%   targets - target data.

%% Dataset Generation

% Get and test the randomised dataset 

% immanentDatasetOpt = createImmanentDataset(2000,20);
% print(immanentDatasetOpt)
% writetable(struct2table(immanentDatasetOpt), 'trainingData.xlsx')

%% Dataset Loading
% Read in the same training data
% x = inputs;
% t = targets;

data = table2struct( readtable('trainingData.xlsx') )

x = [data.length; data.width; data.height];
t = [data.targetVolume];

%% NN Training

% Choose a Training Function
% For a list of all training functions type: help nntrain
% 'trainlm' is usually fastest.
% 'trainbr' takes longer but may be better for challenging problems.
% 'trainscg' uses less memory. Suitable in low memory situations.
% trainFcn = 'trainbr';  
% 
% Create a Fitting Network
% hiddenLayerSize = [10,10];
% net = fitnet(hiddenLayerSize,trainFcn);
% 
% % Setup Division of Data for Training, Validation, Testing
% net.divideParam.trainRatio = 70/100;
% net.divideParam.valRatio = 15/100;
% net.divideParam.testRatio = 15/100;
% 
% % Choose activation functions for each layer
% net.layers{1}.transferFcn = 'logsig'
% net.layers{2}.transferFcn = 'logsig'
%     
% % Train the Network
% [net,tr] = train(net,x,t);

%% NN Loading

load trainedNet
net = trainedNet; 

% Test the Network
y = net(x);
e = gsubtract(t,y);
performance = perform(net,t,y)
testOutput = net(x);
meanSquaredError = mse(net,t,testOutput)

% View the Network
view(net)

% Save the trained NN
% trainedNet = net; 
% save trainedNet;

% Plots
% Uncomment these lines to enable various plots.
figure, plotperform(tr)
figure, plottrainstate(tr)
figure, ploterrhist(e)
figure, plotregression(t,y)
figure, plotfit(net,x,t)

